### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by MaximePremont** [MaximePremont/TwitchStreamDataAPI#8]
**Describe the solution you'd like**
Ignore node modules.

**Comment by Pathholder1806** [comment]
Hey @MaximePremont !
Is this issues about adding a .gitignore file to the root of the project ?

**Comment by MaximePremont** [comment]
Hello @Pathholder1806 , this issue indeed concerns the addition of a simple .gitignore to the root of the project. This allows you to ignore the node modules and the `.vscode/`.

**Comment by Pathholder1806** [comment]
Hey @MaximePremont !
I would like to contribute to this!

**Comment by Pathholder1806** [comment]
Hey @MaximePremont !
I have opened a PR. Kindly review the proposed changes and feel free to suggest any further updates,
